SEMP.UI/Areas/Coleta/Controllers/CadOperadorController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using RAST.BO.Rastreabilidade;
using SEMP.Model.DTO;

namespace SEMP.Areas.Coleta.Controllers
{
	public class CadOperadorController : Controller
	{
		//
		// GET: /Coleta/CadOperador/
		public ActionResult Index(int? codLinha)
		{
			if (codLinha == null) return View(new List<CBPostoDTO>());

			var postos = Geral.ObterPostoPorLinha(codLinha.Value, true);

			return View(postos);
		}

		public ActionResult Alterar(int codLinha, int numPosto)
		{
			var posto = Geral.ObterPosto(codLinha, numPosto);

			return View(posto);
		}

		[HttpPost]
		public ActionResult Alterar(int codLinha, int numPosto, string codDrt)
		{
			var posto = Geral.ObterPosto(codLinha, numPosto);
			posto.CodDRT = codDrt;

			var gravar = Configuracao.EditarPosto(posto);

			return RedirectToAction("Index");
		}

	}
}

SEMP.UI/Areas/Coleta/Views/CadOperador/Alterar.cshtml
@model SEMP.Model.DTO.CBPostoDTO

@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Alterar</title>
</head>
<body>
	@using (Html.BeginForm("Alterar", "CadOperador", FormMethod.Post, new { @class = "form-inline", @role = "form" }))
 {
		@Html.AntiForgeryToken()
		
		<div class="form-horizontal" style="margin-left: 10px;">
			@Html.ValidationSummary(true)
			@Html.HiddenFor(model => model.CodLinha)
			@Html.HiddenFor(model => model.NumPosto)

			<div class="form-group">
				<b>Posto:</b> @Html.ValueFor(model => model.DesPosto)
			</div>
			<br />
			<br />
			<div class="form-group">
				<b>@Html.LabelFor(model => model.CodDRT)</b>
				@Html.EditorFor(model => model.CodDRT)
				@Html.ValidationMessageFor(model => model.CodDRT)
				@Html.EditorFor(model => model.NomFuncionario)
			</div>
			<br />
			<div class="form-group">
				<div style="margin-top: 10px; display: inline-block;">
					@Html.ActionLink("Retornar", "Index", new {codLinha = Model.CodLinha}, new { @class = "bttn bttn-sm bttn-red retornar", @style = "color: white; text-decoration: none;" })
				</div>
				<div style="display: inline-block;">
					<input type="submit" value="Gravar" class="bttn bttn-sm bttn-red" />
				</div>
			</div>
		</div>
 }

	<script>

		$("#CodDRT").blur(function () {
			$.ajax({
				type: "GET",
				url: "/Util/ObterNomFuncionario/",
				data: { codDRT: $("#CodDRT").val() },
				success: function (data) {
					$("#NomFuncionario").val(data);
				}
			});
		});
	</script>
</body>
</html>

SEMP.UI/Areas/Coleta/Views/CadOperador/Index.cshtml
@model IEnumerable<SEMP.Model.DTO.CBPostoDTO>

@{
	ViewBag.Title = "Cadastro de Operador por posto";
	Layout = "~/Views/Shared/_Layout.cshtml";
	var retornologin = (SEMP.Model.VO.RetornoLogin)Session["RetornoLogin"];
	ViewBag.Sistema = "Rastreabilidade";
	ViewBag.Rotina = "Auditor de série";
	if (retornologin != null)
	{
		ViewBag.NomeUsuario = retornologin.NomFuncionario;
	}

	var CodLinha = Request["CodLinha"];
	var Fabrica = Request["fabrica"];


}

<h3>@ViewBag.Title</h3>

<div id="dialog-edit" style="display: none; top: 10px;"></div>

<form name="frmRelatorio" action="" method="post" style="padding-left: 15px;">
	<div class="row">
		<div class="col-xs-20 col-v">
			<div class="col-xs-8">
				<label>F&aacute;brica&#58;</label>
				<select id="cmbFabrica" name="fabrica" class="fabrica">
					<option value="IAC" @{if (Fabrica == "IAC") { WriteLiteral("selected"); }}>IAC</option>
					<option value="IMC" @{if (Fabrica == "IMC") { WriteLiteral("selected"); }}>IMC</option>
					<option value="FEC" @{if (Fabrica == "FEC") { WriteLiteral("selected"); }}>FEC</option>
				</select>
			</div>
			<div class="col-xs-10">
				<label>Linha&#58;</label>
				<select id="CodLinha" name="CodLinha" class="linha">
				</select>
			</div>
			<div class="col-xs-10 right">
				<input type="submit" name="btnEnviar" value="Consultar" class="bttn bttn-sm bttn-red" />
			</div>
		</div>
	</div>
</form>


<table class="table-semp smallrow">
	<thead>
		<tr>
			<th style="width: 100px;"></th>
			<th style="width: 50px;">@Html.DisplayNameFor(model => model.NumPosto)</th>
			<th>@Html.DisplayNameFor(model => model.DesPosto)</th>
			<th style="width: 100px;">@Html.DisplayNameFor(model => model.CodDRT)</th>
			<th>@Html.DisplayNameFor(model => model.NomFuncionario)</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
  {
	  <tr>
		  <td>@Html.ActionLink("Alterar operador", "Alterar", "CadOperador", new { CodLinha = item.CodLinha, NumPosto = item.NumPosto}, new { @class = "lnkEdit" })</td>
		  <td>@Html.DisplayFor(modelItem => item.NumPosto)</td>
		  <td>@Html.DisplayFor(modelItem => item.DesPosto)</td>
		  <td>@Html.DisplayFor(modelItem => item.CodDRT)</td>
		  <td>@Html.DisplayFor(modelItem => item.NomFuncionario)</td>
	  </tr>
  }
	</tbody>

</table>

<br/><br/>

<script type="text/javascript">
	var linha = "@CodLinha";
	var url = "";

	$(document).ready(function () {
		$("#cmbFabrica").change(CarregarLinhas);

		CarregarLinhas();

	});

	function CarregarLinhas() {
		$.ajax({
			type: "GET",
			url: "/posto/GetLinhas/",
			data: { fabrica: $("#cmbFabrica").val() },
			dataType: "json",
			success: function (json) {
				var options = "";
				var selected = "";
				options += '<option value="" selected="selected"> SELECIONE A LINHA </option>';
				$.each(json, function (key, Linhas) {
					if (linha == Linhas.CodLinha) { selected = "selected"; } else { selected = ""; }
					options += '<option value="' + Linhas.CodLinha + '" ' + selected + '>' + Linhas.DesLinha + '</option>';
				});
				$("#CodLinha").html(options);
			}
		});
	}

	$("#dialog-edit").dialog({
		title: 'Cadastrar Operador',
		autoOpen: false,
		resizable: false,
		width: 500,
		height: 180,
		top: 0,
		show: { effect: 'drop', direction: "up" },
		modal: true,
		draggable: true,
		open: function (event, ui) {
			$(".ui-dialog-titlebar-close").hide();
			$(this).html("");
			$(this).load(url);
		}
	});

	$(".lnkEdit").on("click", function (e) {
		// e.preventDefault(); use this or return false
		url = $(this).attr('href');
		$(".ui-dialog-title").html("Cadastrar operador");
		$("#dialog-edit").dialog('open');

		return false;
	});
</script>