SEMP.UI/Areas/Outros/Controllers/CapacLinhaController.cs
using Microsoft.Ajax.Utilities;
using RAST.BO.PM;
using RAST.BO.Rastreabilidade;
using SEMP.Model.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SEMP.Areas.Outros.Controllers
{
	public class CapacLinhaController : Controller
	{


		//
		// GET: /Outros/CapacLinha/
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult Lista(string dataProd, string codLinha, string codModelo)
		{
			var data = DateTime.Now.AddDays(-DateTime.Now.Day).AddDays(1).Date;

			if (!string.IsNullOrWhiteSpace(dataProd))
			{
				data = DateTime.Parse(dataProd);
			}
			else
			{
				data = DateTime.Parse(data.Date.ToShortDateString());
			}

			var capacs = CapacLinha.ObterCapacidades(data, codLinha, codModelo);

			foreach (var item in capacs)
			{
				var cadModelo = ModeloBO.ObterModelo(item.CodModelo);
				if (cadModelo != null){
					item.PostoEntrada = cadModelo.PostoEntrada;
				}
			}

			return View(capacs);
		}

		//
		// GET: /Outros/CapacLinha/Create
		public ActionResult Create()
		{
			return View();
		}

		//
		// POST: /Outros/CapacLinha/Create
		[HttpPost]
		public ActionResult Edit(CapacLinhaDTO capac, string PostoEntrada)
		{
			try
			{
				if (!CapacLinha.VerificaSeLinhaExiste(capac.CodLinha))
				{
					var json = new
					{
						message = "Código de linha inválido.",
						retorno = false
					};
					return Json(json, JsonRequestBehavior.AllowGet);
				}
				else if (!CapacLinha.VerificaSeModeloExiste(capac.CodModelo))
				{
					var json = new
					{
						message = "Código de modelo inválido.",
						retorno = false
					};
					return Json(json, JsonRequestBehavior.AllowGet);
				}
				else
				{
					CapacLinha.Gravar(capac);

					if (!String.IsNullOrEmpty(PostoEntrada))
					{
						var cadModelo = ModeloBO.ObterModelo(capac.CodModelo);
						if (cadModelo != null)
						{
							cadModelo.PostoEntrada = Convert.ToBoolean(PostoEntrada);
						}
						else
						{
							cadModelo = new CBModeloDTO()
							{
								CodModelo = capac.CodModelo,
								PostoEntrada = Convert.ToBoolean(PostoEntrada)
							};
						}
						ModeloBO.AtualizaModelo(cadModelo);
					}

					var json = new
					{
						message = "Capacidade inserida com sucesso.",
						retorno = true
					};
					return Json(json, JsonRequestBehavior.AllowGet);
				}
			}
			catch (Exception ex)
			{

				var mensagem = ex.InnerException != null ? ex.InnerException.InnerException != null ? ex.InnerException.InnerException.Message : ex.InnerException.Message : ex.Message;

				var json = new
				{
					message = "Não foi possível gravar. (" + mensagem + ")",
					retorno = false
				};
				return Json(json, JsonRequestBehavior.AllowGet);
			}
		}

		//
		// GET: /Outros/CapacLinha/Edit/5
		public ActionResult Edit(string dataProd, string codLinha, string codModelo)
		{
			DateTime data = DateTime.Now.Date;

			if (!string.IsNullOrWhiteSpace(dataProd))
			{
				data = DateTime.Parse(dataProd);
			}
			if (!String.IsNullOrEmpty(codLinha))
			{
				var origem = CapacLinha.ObterCapacidade(data, codLinha, codModelo);

				var cadModelo = ModeloBO.ObterModelo(codModelo);
				if (cadModelo != null){
					ViewBag.postoEntrada = cadModelo.PostoEntrada;
				}

				return View(origem);
			}

			return View();
		}

		//
		// POST: /Coleta/Origem/Edit/5
		[HttpPost]
		public ActionResult EditOld(CapacLinhaDTO capac)
		{
			try
			{
				CapacLinha.Gravar(capac);

				return Json(true, JsonRequestBehavior.AllowGet);
			}
			catch
			{
				return Json(false, JsonRequestBehavior.AllowGet);
			}
		}

		//
		// GET: /Outros/CapacLinha/Delete/5
		public ActionResult Delete(string dataProd, string codLinha, string codModelo)
		{
			DateTime data = DateTime.Now.Date;

			if (!string.IsNullOrWhiteSpace(dataProd))
			{
				data = DateTime.Parse(dataProd);
			}

			var origem = CapacLinha.ObterCapacidade(data, codLinha, codModelo);

			return View(origem);
		}

		//
		// POST: /Outros/CapacLinha/Delete/5
		[HttpPost]
		public ActionResult Delete(CapacLinhaDTO capac)
		{
			try
			{
				CapacLinha.Remover(capac);

				return RedirectToAction("Index");
			}
			catch
			{
				return RedirectToAction("Index");
			}
		}

		/// <summary>
		/// Rotina para clonar um mês para o mês atual
		/// </summary>
		/// <param name="mesRef"></param>
		/// <returns></returns>
		public string ClonarMes(string mesRef, string mesDest)
		{

			var data = DateTime.Parse(mesRef);
			var dataDest = DateTime.Parse(mesDest);

			var clonar = CapacLinha.ClonarMes(data, dataDest);

			return clonar.ToString();
		}

	}
}

SEMP.UI/Areas/Outros/Views/CapacLinha/Create.cshtml
@model SEMP.Model.DTO.CapacLinhaDTO

@{
	ViewBag.Title = "Create";
}
@Scripts.Render("~/bundles/jqueryval")

<style>
	.ui-datepicker-calendar
	{
		display: none;
	}

	.ui-datepicker
	{
		width: 200px !important;
	}

	.field-validation-error
	{
		width: 90%;
		font-size: 8pt;
		display: block;
		position: relative;
		top: -65px;
		height: 0px;
		z-index: 999;
	}

		.field-validation-error span
		{
			border-radius: 4px;
			padding: 5px 5px 5px 5px;
			background-color: #FFE6BF;
			position: relative;
			border: 2px solid red;
		}

			.field-validation-error span:after
			{
				content: ' ';
				height: 0;
				position: absolute;
				width: 0;
				border: 10px solid transparent;
				border-top-color: #FFE6BF;
				top: 100%;
				left: 10px;
			}

			.field-validation-error span:before
			{
				content: ' ';
				height: 0;
				position: absolute;
				width: 0;
				border: 13px solid transparent;
				border-top-color: red;
				top: 100%;
				left: 7px;
			}
</style>
<script src="@Scripts.Url("~/Scripts/jquery.maskedinput.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", "CapacLinha", FormMethod.Post, new { @class = "form-inline", @role = "form", @name = "frmCapacidade", id = "frmCapacidade" }))
{
	@Html.AntiForgeryToken()
	@Html.ValidationSummary(true)

	<div class="row">
		<div class="col-md-6" style="width: 210px;">
			@Html.LabelFor(model => model.DatProducao)
			@Html.TextBoxFor(model => model.DatProducao, new { @class = "form-control input-sm", @style="width: 85px;", @Value = DateTime.Now.ToString("MM/yyyy") })

		</div>
		<div class="col-md-6" style="width: 250px;">
			@Html.LabelFor(model => model.CodLinha, new {@style="float: left; margin-top: 5px;"})
			<div class="input-group input-group-sm">
				@Html.TextBoxFor(model => model.CodLinha, new { @style = "width: 60px", @class="form-control" })
				@Html.TextBoxFor(model => model.DescricaoLinha, new { @disabled = "disabled", @class="input-group-addon", @style="width: 125px;" })
			</div>
			@Html.ValidationMessageFor(model => model.CodLinha)
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			@Html.LabelFor(model => model.CodModelo)
			<div class="input-group input-group-sm">
				@Html.TextBoxFor(model => model.CodModelo, new { @style = "width: 60px", @maxlength = "6", @class="form-control" })
				@Html.TextBoxFor(model => model.DescricaoModelo, new { @disabled = "disabled", @style = "width: 280px", @class="input-group-addon" })
			</div>
			@Html.ValidationMessageFor(model => model.CodModelo)
		</div>
	</div>

	<div class="row">
		<div class="col-md-4" style="width: 180px; padding-right: 1px;">
			@Html.LabelFor(model => model.QtdCapacLinha, new {@style = "float: left; margin-top: 5px; "})&nbsp;
			@Html.TextBoxFor(model => model.QtdCapacLinha, new { @style = "width: 40px" })
			@Html.ValidationMessageFor(model => model.QtdCapacLinha)
		</div>
		<div class="col-md-4" style="width: 160px; padding-left: 1px;">
			@Html.LabelFor(model => model.QtdCapacMaxima)
			@Html.TextBoxFor(model => model.QtdCapacMaxima, new { @style = "width: 40px" })
			@Html.ValidationMessageFor(model => model.QtdCapacMaxima)
		</div>
		<div class="col-md-4" style="width: 100px;">
			@Html.LabelFor(model => model.NumTurno)
			@Html.TextBoxFor(model => model.NumTurno, new { @style = "width: 30px" })
			@Html.ValidationMessageFor(model => model.NumTurno)
		</div>
	</div>

	<div class="row" style="margin-top: 15px;">
		<div class="form-group">
			<div style=" margin-right: 10px; display: inline-block;">
				<input type="button" onclick="$('#dialog-edit').dialog('close');" class="bttn bttn-sm bttn-red" value="Cancelar" />
			</div>
			<div style="display: inline-block;">
				<input type="button" value="Gravar" class="bttn bttn-sm bttn-red" onclick="gravar()" />
			</div>
		</div>
	</div>

}

<script>
	$(document).ready(function () {
		$("#DatProducao").datepicker(
		{
			changeMonth: true,
			changeYear: true,
			showButtonPanel: true,
			dateFormat: 'mm/yy',

			onClose: function () {
				var iMonth = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
				var iYear = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
				$(this).datepicker('setDate', new Date(iYear, iMonth, 1));
			}

		});

		$("#DatProducao").mask("99/9999");

		$("#CodLinha").mask("999.99-9", { placeholder: " " });


		$("#CodLinha").blur(function () {
			$("#DescricaoLinha").val("");
			$.ajax({
				type: "GET",
				url: "/Util/ObterDescricaoLinha/",
				data: { CodLinha: $("#CodLinha").val() },
				success: function (data) {
					$("#DescricaoLinha").val(data);
				}
			});
		});

		$("#CodModelo").blur(function () {
			$("#DescricaoModelo").val("");
			$.ajax({
				type: "GET",
				url: "/Util/ObterDescricaoItem/",
				data: { CodItem: $("#CodModelo").val() },
				success: function (data) {
					$("#DescricaoModelo").val(data);
				}
			});
		});
	});

	function gravar() {
		$("#frmCapacidade").validate({
			onfocusout: true
		}).form();

		$("#DatProducao").val("01/" + $("#DatProducao").val());

		if ($("#frmCapacidade").valid()) {

			$.ajax({
				type: "POST",
				url: "/CapacLinha/Create/",
				data: $("#frmCapacidade").serialize(),
				dataType: "json",
				success: function (json) {
					if (json.retorno == true) {
						alert("Capacidade inserida com sucesso!");
						$("#frmCapacidade")[0].reset();
					} else {
						alert(json.message);
					}
				},
				error: function (xhr) {
					alert("Não foi possível adicionar: " + xhr);
				}
			});

		}
	}

</script>

SEMP.UI/Areas/Outros/Views/CapacLinha/Delete.cshtml
@model SEMP.Model.DTO.CapacLinhaDTO

<div style="width: 400px;text-align: center;margin-left: auto;margin-right: auto;">
	<h4>Tem certeza de que deseja remover esse registro?</h4>

	<fieldset>

		<div class="display-label" style="font-weight:bold; margin-top:10px;">
			 @Html.DisplayNameFor(model => model.CodLinha)
		</div>
		<div class="display-field">
			@Html.DisplayFor(model => model.CodLinha)
		</div>

		<div class="display-label" style="font-weight:bold;">
			 @Html.DisplayNameFor(model => model.CodModelo)
		</div>
		<div class="display-field">
			@Html.DisplayFor(model => model.CodModelo)
		</div>
		@using (Html.BeginForm())
		{

			@Html.HiddenFor(model => model.DatProducao)
			@Html.HiddenFor(model => model.NumTurno)
		 
			@Html.AntiForgeryToken()

			<div class="form-actions no-color" style="margin-top: 10px;">
				<div style="margin-top: 10px; display: inline-block;">
					<input type="button" onclick="$('#dialog-edit').dialog('close');" class="bttn bttn-sm bttn-red" value="Cancelar" />
				</div>
				<div style="display: inline-block;">
					<input type="submit" value="Apagar" class="bttn bttn-sm bttn-red" />
				</div>
			</div>
	 }
	</fieldset>
</div>

SEMP.UI/Areas/Outros/Views/CapacLinha/Edit.cshtml
@model SEMP.Model.DTO.CapacLinhaDTO

@{
	ViewBag.Title = "Editar";

	var data = DateTime.Now.ToString("MM/yyyy");
	bool editar = false;


	if (Model != null)
	{
		data = Model.DatProducao.ToString("MM/yyyy");
		editar = true;
	}

	bool? postoEntrada = ViewBag.postoEntrada;
}

@Scripts.Render("~/bundles/jqueryval")

<style>
	.ui-datepicker-calendar {
		display: none;
	}

	.ui-datepicker {
		width: 200px !important;
	}

	.field-validation-error {
		width: 90%;
		font-size: 8pt;
		display: block;
		position: relative;
		top: -65px;
		height: 0px;
		z-index: 999;
	}

		.field-validation-error span {
			border-radius: 4px;
			padding: 5px 5px 5px 5px;
			background-color: #FFE6BF;
			position: relative;
			border: 2px solid red;
		}

			.field-validation-error span:after {
				content: ' ';
				height: 0;
				position: absolute;
				width: 0;
				border: 10px solid transparent;
				border-top-color: #FFE6BF;
				top: 100%;
				left: 10px;
			}

			.field-validation-error span:before {
				content: ' ';
				height: 0;
				position: absolute;
				width: 0;
				border: 13px solid transparent;
				border-top-color: red;
				top: 100%;
				left: 7px;
			}
</style>
<script src="@Scripts.Url("~/Scripts/jquery.maskedinput.js")" type="text/javascript"></script>

@using (Html.BeginForm("Edit", "CapacLinha", FormMethod.Post, new { @class = "form-inline", @role = "form", @id = "frmOrigem", @name = "frmOrigem" }))
{
	@Html.AntiForgeryToken()
	@Html.ValidationSummary(true)

	<div class="row" style="margin-bottom: 5px;">
		<div class="col-sm-4">
			<label for="DatProducao">Mês</label>
			@if (editar)
			{
			@Html.TextBoxFor(model => model.DatProducao, new { disabled = "disabled", @style = "width: 85px;", @class = "form-control input-sm", @Value = data })
			}
			else
			{
			@Html.TextBoxFor(model => model.DatProducao, new { @style = "width: 85px;", @class = "form-control input-sm", @Value = data })
			}
		</div>
		<div class="col-sm-8">
			@Html.LabelFor(model => model.CodLinha, new { @style = "float: left; margin-top: 5px;" })
			<div class="input-group input-group-sm">
				@if (editar)
				{
				@Html.TextBoxFor(model => model.CodLinha, new { @disabled = "disabled", @style = "width: 70px", @class = "form-control" })
				}
				else
				{
				@Html.TextBoxFor(model => model.CodLinha, new { @style = "width: 70px", @class = "form-control" })
				}
				@Html.TextBoxFor(model => model.DescricaoLinha, new { @disabled = "disabled", @class = "input-group-addon", @style = "width: 125px;" })
			</div>
			@Html.ValidationMessageFor(model => model.CodLinha)
		</div>
	</div>

	<div class="row" style="margin-bottom: 5px;">
		<div class="col-sm-12">
			@Html.LabelFor(model => model.CodModelo)
			<div class="input-group input-group-sm">
				@if (editar)
				{
				@Html.TextBoxFor(model => model.CodModelo, new { @disabled = "disabled", @style = "width: 60px", @class = "form-control" })
				}
				else
				{
				@Html.TextBoxFor(model => model.CodModelo, new { @style = "width: 60px", @class = "form-control" })
				}
				@Html.TextBoxFor(model => model.DescricaoModelo, new { @disabled = "disabled", @style = "width: 288px", @class = "input-group-addon" })
			</div>
			@Html.ValidationMessageFor(model => model.CodModelo)
		</div>
	</div>

	<div class="row" style="margin-bottom: 5px;">
		<div class="col-sm-6">
			@Html.LabelFor(model => model.QtdCapacLinha)
			@Html.TextBoxFor(model => model.QtdCapacLinha, new { @class="form-control input-sm text-right", @style = "width: 60px" })
			@Html.ValidationMessageFor(model => model.QtdCapacLinha)
		</div>
		<div class="col-sm-6">
			@Html.LabelFor(model => model.QtdCapacMaxima)
			@Html.TextBoxFor(model => model.QtdCapacMaxima, new { @class = "form-control input-sm text-right", @style = "width: 52px" })
			@Html.ValidationMessageFor(model => model.QtdCapacMaxima)
		</div>
	</div>
	<div class="row">
		<div class="col-sm-7">
			<label class="control-label" for="PostoEntrada">Posto de Entrada</label>
			<select name="PostoEntrada" id="PostoEntrada" class="form-control input-sm">
				<option value="" @if (postoEntrada == null) { Write("selected"); }>Não configurado</option>
				<option value="false" @if (postoEntrada == false) { Write("selected"); }>Primeiro Posto</option>
				<option value="true" @if (postoEntrada == true) { Write("selected"); }>Último Posto</option>
			</select>
		</div>
		<div class="col-sm-4">
			@Html.LabelFor(model => model.NumTurno)
			@Html.TextBoxFor(model => model.NumTurno, new { @class = "form-control input-sm text-right", @style = "width: 65px" })
			@Html.ValidationMessageFor(model => model.NumTurno)
		</div>

	</div>

	<div class="row" style="margin-top: 10px;">
		<div class="col-sm-6 col-sm-offset-6">
			<div class="btn-group">
				<input type="button" onclick="$('#dialog-edit').dialog('close');" class="btn btn-danger" value="Cancelar" />
				<input type="button" value="Gravar" class="btn btn-danger" onclick="gravar()" />
			</div>
		</div>
	</div>

}

<script>

	jQuery(function ($) {
		$("#CodLinha").mask("999.99-9", { placeholder: " " });
		$("#QtdCapacLinha").focus();
	});

	function gravar() {
		$("#DatProducao").removeAttr("disabled");
		$("#CodLinha").removeAttr("disabled");
		$("#CodModelo").removeAttr("disabled");
		$("#DescricaoLinha").removeAttr("disabled");
		$("#DescricaoModelo").removeAttr("disabled");

		$.ajax({
			type: "POST",
			url: "/CapacLinha/Edit/",
			data: $("#frmOrigem").serialize(),
			dataType: "json",
			success: function (json) {
				alert(json.message);
				btnEnviar_Click();
				$('#dialog-edit').dialog('close');
				/*if (json == true) {
					alert("Capacidade alterada com sucesso.");
					document.location.href = "/Outros/CapacLinha/";
				} else {
					alert("Não foi possível gravar.");
				}*/
			},
			error: function (xhr) {
				alert("Não foi possível alterar: " + xhr);
			}
		});
	}

</script>

SEMP.UI/Areas/Outros/Views/CapacLinha/Index.cshtml
@model IEnumerable<SEMP.Model.DTO.CapacLinhaDTO>

@{
	ViewBag.Title = "Listagem de Capacidade";
	Layout = "~/Views/Shared/_Layout.cshtml";

	ViewBag.Sistema = "Outros";
	ViewBag.Rotina = "Cadastro de Capacidade";

	var mesAtual = DateTime.Now.AddDays(-DateTime.Now.Day).AddDays(1).ToString("MM/yyyy");

	var retornologin = (SEMP.Model.VO.RetornoLogin)Session["RetornoLogin"] ?? new SEMP.Model.VO.RetornoLogin { CodDRT = "", UsuarioCracha = false, NomFuncionario = "", NomUsuario = "", Depto = "", Cargo = "" };

	//var depto = retornologin.Depto ?? "";
	var acessoCapac = SEMP.Helpers.Extensions.Permissao("CadCapacidade", retornologin);
}

<style>
	.ui-datepicker-calendar
	{
		display: none;
	}
	.ui-datepicker
	{
		width: 200px !important;
	}
</style>
<script src="@Scripts.Url("~/Scripts/jquery.maskedinput.js")" type="text/javascript"></script>

@Scripts.Render("~/bundles/excelexport")

<h3>@ViewBag.Title</h3>

<div id="dialog-edit" style="display: none; top: 10px;"></div>


<form name="frmRelatorio" action="/Outros/CapacLinha/" method="POST" class="form-inline">
	<div class="row">
		<div class="col-md-2">
			<label>Mês Ref:</label>
			<input type="text" name="dataProd" id="dataProd" value="@mesAtual" class="form-control" style="width:80px !important;"/>
		</div>
		<div class="col-md-2" style="width: 230px;">
			<label style="float: left; margin-top: 5px;">Linha: </label>
			<div class="input-group input-group-sm">
				<input type="text" name="pCodLinha" id="pCodLinha" class="form-control" style="width: 60px;"/>
				<input type="text" name="pDesLinha" id="pDesLinha" class="input-group-addon" style="width: 100px;" disabled="disabled" />
			</div>
		</div>
		<div class="col-md-3">
			<label style="float: left; margin-top: 5px; ">Modelo&nbsp;:</label>
			<div class="input-group input-group-sm">
				<input type="text" name="pCodModelo" id="pCodModelo" class="form-control" style="width: 60px;"/>
				<input type="text" name="pDesModelo" id="pDesModelo" class="input-group-addon" style="width: 150px;" disabled="disabled" />
			</div>
		</div>
		<div class="col-md-4">
			<div class="btn-group">
				<input type="button" id="btnExportar" name="btnExportar" value="Exportar Excel" class="btn btn-sm btn-success" />
				@if (acessoCapac)
				{<input type="button" name="btnNovo" id="btnNovo" value="Novo" class="btn btn-sm btn-danger" />}
				<input type="button" name="btnEnviar" value="Consultar" class="btn btn-sm btn-danger" onclick="btnEnviar_Click();" />
			</div>
		</div>
	</div>
    <div class="row">
        <div class="col-md-2">
            <label>Mês Destino:</label>
            <input type="text" name="dataDest" id="dataDest" value="@mesAtual" class="form-control" style="width:80px !important;" />
        </div>
        <div class="col-md-2" style="margin-left: -60px;">
            @if (acessoCapac){<input type="button" name="btnClonar" id="btnClonar" value="Clonar" class="btn btn-sm btn-danger" />}
        </div>
        <div class="col-md-8">&nbsp;</div>
    </div>
</form>

<div id="conteudo"></div>
<div id="carregando" style="display: none;">
	<div style="position: relative; z-index: 1; left: 0; top: 0; width: 100%; height: 100%; text-align: center; background-color: #000000; background-color: rgba(0, 0, 0, 0.14);">
		<img id="imgCarregando" src="/Images/carregando.gif" />
	</div>
</div>


<script>
	var url = "";

	$(document).ready(function() {

		$("#dataProd").datepicker(
		{
			changeMonth: true,
			changeYear: true,
			showButtonPanel: true,
			dateFormat: 'mm/yy',

			onClose: function() {
				var iMonth = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
				var iYear = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
				$(this).datepicker('setDate', new Date(iYear, iMonth, 1));
			}

		});

		$("#dataDest").datepicker(
        {
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'mm/yy',

            onClose: function () {
                var iMonth = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var iYear = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $(this).datepicker('setDate', new Date(iYear, iMonth, 1));
            }

        });


		$("#btnExportar").click(function() {

			$("#tblDados").btechco_excelexport({
				containerid: "tblDados",
				datatype: $datatype.MVC
			});
		});

		$("#dialog-edit").dialog({
			title: 'Editar Capacidade',
			autoOpen: false,
			resizable: false,
			width: 500,
			height: 230,
			top: 0,
			show: { effect: 'drop', direction: "up" },
			modal: true,
			draggable: true,
			open: function(event, ui) {
				$(".ui-dialog-titlebar-close").hide();
				$(this).html("");
				$(this).load(url);
			}
		});

		$("#btnNovo").on("click", function(e) {
			url = "/Outros/CapacLinha/Edit/";
			$(".ui-dialog-title").html("Nova Capacidade");
            $("#dialog-edit").dialog('open');
            $("#dialog-edit").css("height", 230);

			return false;
		});

		$("#btnClonar").on("click", function (e) {

		    var mes = $("#dataProd").val();
		    var mesDest = $("#dataDest").val();

			if (mesDest == mes) {
				alert("Não é possível clonar o próprio mês");
				return false;
			}

			var r = confirm("Confirma clonar esse mês?");

			if (r == true) {

				$.ajax({
					type: "GET",
					url: "/Outros/CapacLinha/ClonarMes/",
					data: { mesRef: mes, mesDest: mesDest},
					success: function (data) {
						alert("Mês clonado!");
					}
				});
			}

			return false;
		});

		$("#pCodLinha").mask("999.99-9");
		$("#pCodLinha").blur(function () {
			$("#pDesLinha").val("");
			$.ajax({
				type: "GET",
				url: "/Util/ObterDescricaoLinha/",
				data: { CodLinha: $("#pCodLinha").val() },
				success: function (data) {
					$("#pDesLinha").val(data);
				}
			});
		});

		$("#pCodModelo").blur(function () {
			$("#pDesModelo").val("");
			$.ajax({
				type: "GET",
				url: "/Util/ObterDescricaoItem/",
				data: { CodItem: $("#pCodModelo").val() },
				success: function (data) {
					$("#pDesModelo").val(data);
				}
			});
		});

		btnEnviar_Click();

	});

	function btnEnviar_Click() {
		$("#conteudo").html($('#carregando').html());

		$.ajax({
			type: "GET",
			url: "/Outros/CapacLinha/Lista/",
			data: {
				dataProd: $("#dataProd").val(),
				codModelo: $("#pCodModelo").val(),
				codLinha: $("#pCodLinha").val(),
			},
			success: function (data) {
				$("#conteudo").html(data);
				$(".linkEdit").on("click", function (e) {
					// e.preventDefault(); use this or return false
					url = $(this).attr('href');
					$(".ui-dialog-title").html("Editar Capacidade");
					$("#dialog-edit").dialog('open');
					$("#dialog-edit").css("height", 230);

					return false;
				});

				$(".lnkDelete").on("click", function (e) {
					url = $(this).attr('href');
					$(".ui-dialog-title").html("Deletar Capacidade");
					$("#dialog-edit").dialog('open');
					$("#dialog-edit").css("height", 180);

					return false;
				});
				$('a').tooltip();
			},
			error: function (data) {
				$("#conteudo").html(data);
			}
		});
	}

</script>