SEMP.UI/Areas/Coleta/Controllers/ConfiguracaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RAST.BO.Rastreabilidade;
using SEMP.Model.VO.Rastreabilidade;
using SEMP.Model.DTO;
using SEMP.Model.VO;
using SEMP.Model;
using System.Reflection;
using System.Text.RegularExpressions;

namespace SEMP.Areas.Coleta.Controllers
{
	/// <summary>
	/// Classe que controla as Action da funcionalidade Configuração
	/// </summary>
	public class ConfiguracaoController : Controller
	{				
		/// <summary>
		/// Método Index controla a pagina inicial do controller Configuracao.
		/// </summary>
		/// <returns>Retorna a View Index.cshtml</returns>
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult Parametros() {

			var enviaApontamento = Geral.ObterAcessosBarApontamento();

			ViewBag.EnviaApontamento = enviaApontamento;

			return View();
		}

		#region Etiquetas
		public ActionResult Etiquetas(string codLinha)
		{

			List<CBEtiquetaDTO> lista = Configuracao.ObterEtiquetas(codLinha);
			
		
			return View(lista);
		}


		public ActionResult EtiquetasPartial(string codLinha)
		{

			List<CBEtiquetaDTO> lista = Configuracao.ObterEtiquetas(codLinha);


			return PartialView(lista);
		}
		
		#endregion

		/// <summary>
		/// Método que controla a página que exibe todas as linhas da produção
		/// </summary>
		/// <returns>Retorna a View Linha.cshtml</returns>
		public ActionResult Linha(string flgStatus, string fase)
		{
			Configuracao config = new Configuracao();
			
			var dados = config.ObterLinhas();

			ViewBag.Linhas = dados;

			if (String.IsNullOrEmpty(flgStatus) || flgStatus == "1")
			{
				dados = dados.Where(x => x.FlgAtivo == "1").ToList();
			}
			else if (String.IsNullOrEmpty(flgStatus) || flgStatus == "0")
			{
				dados = dados.Where(x => x.FlgAtivo == "0").ToList();
			}

			if (!string.IsNullOrEmpty(fase))
			{
				dados = dados.Where(x => x.Setor == fase).ToList();
			}

			return View(dados.OrderBy(x => x.Setor).ThenBy(y => y.CodLinhaT1 != null ? y.CodLinhaT1.Substring(3) : y.DesLinha));
		}

		/// <summary>
		/// Método que controla a página de edição de linha
		/// </summary>
		/// <param name="id">Parâmetro com o código da linha que será editada</param>
		/// <returns>Retorna a View EditLinhas.cshtml</returns>
		public ActionResult EditLinhas(int id)
		{			
			Configuracao config = new Configuracao();

			CBLinhaDTO linha = config.ObterLinha(id);

			if (linha == null)
			{
				return HttpNotFound();
			}
			ViewBag.CodLinha = new SelectList("CodLinha", linha.CodLinha);

			var configuracao = new Configuracao();
			var fases = configuracao.ObterFases();
			ViewBag.fases = fases;

			return View(linha);
		}

		public ActionResult ViewLinha(int id)
		{
			Configuracao config = new Configuracao();

			CBLinhaDTO linha = config.ObterLinha(id);

			if (linha == null)
			{
				return HttpNotFound();
			}
			ViewBag.CodLinha = new SelectList("CodLinha", linha.CodLinha);

			var configuracao = new Configuracao();
			var fases = configuracao.ObterFases();
			ViewBag.fases = fases;

			var horarios = Configuracao.ObterHorarioIntervalo(id);
			var postos = configuracao.ObterPostos(id);

			ViewBag.Postos = postos;
			ViewBag.Horarios = horarios;

			return View(linha);
		}

		public ActionResult Postos(int id )
		{
			Configuracao config = new Configuracao();

            
            ViewBag.CodLinha = id;
            ViewBag.DesLinha = Configuracao.ObterDesLinha(id);
           

			return View(config.ObterPostos(id).ToList());
		}

        public ActionResult PostosTablet(int codLinha, int tipoPosto)
        {

            int NumPosto = Configuracao.ObterTipoPostoTablet(codLinha, tipoPosto);

            
            return Json(NumPosto, JsonRequestBehavior.AllowGet);
        }

		public ActionResult Horario()
		{
			Configuracao config = new Configuracao();

			return View(config.ObterHorarios().ToList());
		}


        public ActionResult PostoResumo(int CodLinha, int NumPosto)
        {
            Configuracao config = new Configuracao();

            ViewBag.DesPosto = Configuracao.ObterDesPosto(NumPosto);
            ViewBag.DesLinha = Configuracao.ObterDesLinha(CodLinha);


            CBPostoDTO posto = config.ObterPosto(CodLinha, NumPosto);


            if (posto == null)
            {
                return HttpNotFound();
            }

            return View(posto);

        }

		public ActionResult EditPosto(int CodLinha, int NumPosto)
		{		
			Configuracao config = new Configuracao();

			CBPostoDTO posto = config.ObterPosto(CodLinha, NumPosto);
			List<CBTipoPostoDTO> CodTipoPosto = config.ObterTiposPosto();
			List<CBTipoAmarraDTO> TipoAmarra = config.ObterTiposAmarra();

			if (posto == null)
			{
				return HttpNotFound();
			}
			
			ViewBag.CodLinha = new SelectList("CodLinha", posto.CodLinha);
			ViewBag.CodTipoPosto = new SelectList(CodTipoPosto.ToList(), "CodTipoPosto", "DesTipoPosto", posto.CodTipoPosto);		
			return View(posto);
		}

		public ActionResult EditHorario(int id)
		{
			Configuracao config = new Configuracao();

			CBHorarioDTO horario = config.ObterHorario(id);

			if (horario == null)
			{
				return HttpNotFound();
			}
			ViewBag.CodLinha = new SelectList("idHorario", horario.idHorario);
			return View(horario);
		}

		/// <summary>
		/// Método que faz a chamada para adicionar nova linha de produção
		/// </summary>
		/// <returns></returns>
		public ActionResult AddLinha()
		{
			var configuracao = new Configuracao();
			var fases = configuracao.ObterFases();
			ViewBag.fases = fases;

			return View();
		}

		/// <summary>
		/// Método que faz a chamada para adicionar nova linha de produção
		/// </summary>
		/// <returns></returns>
		public ActionResult AddHorario()
		{
			return View();
		}

		/// <summary>
		/// Método que faz chamada para página de adição de posto
		/// </summary>
		/// <returns></returns>
		/*public ActionResult AddPosto()
		{
			Configuracao config = new Configuracao();
			
			List<CBLinhaDTO> linha = config.ObterLinhas();
			List<CBTipoPostoDTO> CodTipoPosto = config.ObterTiposPosto();

			ViewBag.CodLinha = new SelectList(linha.ToList(), "CodLinha", "DesLinha", linha.FirstOrDefault());
			ViewBag.CodTipoPosto = new SelectList(CodTipoPosto.ToList(), "CodTipoPosto", "DesTipoPosto", CodTipoPosto.FirstOrDefault());

			return View();
		}*/

		public ActionResult AddPosto(int? id)
		{
			Configuracao config = new Configuracao();

			List<CBTipoPostoDTO> CodTipoPosto = config.ObterTiposPosto();

			var postos = config.ObterPostos(id ?? 0);
			var ultPosto = postos.Count() > 0 ? postos.Max(x => x.NumPosto) : 0;
			

			ViewBag.CodLinha = id;
			ViewBag.ultPosto = ultPosto;
			ViewBag.CodTipoPosto = new SelectList(CodTipoPosto.ToList(), "CodTipoPosto", "DesTipoPosto", CodTipoPosto.FirstOrDefault());

			return View(new CBPostoDTO());
		}

		/// <summary>
		/// Método que faz chamada para a página de Configuração de Máscara
		/// </summary>
		/// <returns></returns>
		public ActionResult Mascara()
		{
			Configuracao config = new Configuracao();

			return View(config.ObterPerfilMascara().ToList());
		}

		public ActionResult AddMascara()
		{			

			return View();
		}

		/// <summary>
		/// Método para exibir as linhas de produção
		/// </summary>
		/// <param name="sidx"></param>
		/// <param name="sord"></param>
		/// <param name="page"></param>
		/// <param name="rows"></param>
		/// <returns></returns>
		public ActionResult ObterLinhas(string sidx, string sord, int page, int rows)
		{
			Configuracao config = new Configuracao();
			var context = config.ObterLinhas();


			int pageIndex = Convert.ToInt32(page) - 1;
			int pageSize = rows;
			int totalRecords = context.Count();
			int totalPages = (int)Math.Ceiling((float)totalRecords / (float)pageSize);

			var authors = context.OrderBy(a => sord).Skip(pageIndex * pageSize).Take(pageSize).ToList();

			var jsonData = new
			{
				total = totalPages,
				page,
				records = totalRecords,
				rows = (from n in authors
						select new
						{
							i = n.CodLinha,
							cell = new string[] { n.CodLinha.ToString(), n.DesLinha, n.Setor, n.Familia, n.CodLinhaT1 }
						}).ToArray()
			};

			return Json(jsonData, JsonRequestBehavior.AllowGet);
		}

		public JsonResult EditarLinha(string DesLinha, string DesObs, string Setor, string Familia, string CodLinhaT1)
		{

			String retorno = "";

			return Json(retorno, JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult EditLinhas(CBLinhaDTO tbl_cblinha)
		{			
			Configuracao config = new Configuracao();

			Boolean gravar = config.EditarLinha(tbl_cblinha.CodLinha, tbl_cblinha.DesLinha, tbl_cblinha.DesObs, tbl_cblinha.Setor, tbl_cblinha.Familia, tbl_cblinha.CodLinhaT1,
								tbl_cblinha.CodLinhaT2, tbl_cblinha.CodLinhaT3, tbl_cblinha.FlgAtivo, tbl_cblinha.CodLinhaOrigem, tbl_cblinha.SetorOrigem);

			if(gravar)
				ViewBag.JS = "alert('Linha editada com sucesso.'); location.href ='/Coleta/Configuracao/Linha/'";
			else
				ViewBag.JS = "Não foi possível editar a linha. Tente novamente.";

			return View(tbl_cblinha);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult EditPosto(CBPostoDTO tbl_cbposto)
		{
			Configuracao config = new Configuracao();
						
			Boolean gravar = config.EditarPosto(tbl_cbposto.CodLinha, tbl_cbposto.NumPosto, tbl_cbposto.CodTipoPosto, tbl_cbposto.DesPosto, 
												tbl_cbposto.FlgAtivo, tbl_cbposto.NumSeq, tbl_cbposto.flgObrigatorio.HasValue && (bool)tbl_cbposto.flgObrigatorio, tbl_cbposto.flgPedeAP,
												tbl_cbposto.flgImprimeEtq, tbl_cbposto.TempoLeitura ?? 0, tbl_cbposto.TipoEtiqueta ?? 0,
                                                tbl_cbposto.TempoCiclo ?? 0, tbl_cbposto.FlgGargalo, tbl_cbposto.flgValidaOrigem.HasValue && (bool)tbl_cbposto.flgValidaOrigem, tbl_cbposto.MontarLote.HasValue && (bool)tbl_cbposto.MontarLote,
												tbl_cbposto.FlgTipoTerminal);
												

			if (gravar)

SEMP.UI/Areas/Outros/Controllers/LinhaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RAST.BO.PM;
using SEMP.Model.DTO;

namespace SEMP.Areas.Outros.Controllers
{
	public class LinhaController : Controller
	{
		//
		// GET: /Outros/Linha/
		public ActionResult Index()
		{
			return View();
		}

		//
		// GET: /Outros/Linha/Details/5
		public ActionResult Lista(string flgAtivo, string flgTipo)
		{
			var dados = CadLinha.ObterLinhas();

			if (flgAtivo != null && flgAtivo.Equals("S"))
			{
				dados = dados.Where(x => x.FlgAtivo == "S").ToList();
			}
			else if (flgAtivo != null && flgAtivo.Equals("N"))
			{
				dados = dados.Where(x => x.FlgAtivo == "N").ToList();
			}

			if (!String.IsNullOrEmpty(flgTipo) && flgTipo.Equals("P"))
			{
				dados = dados.Where(x => x.CodLinha.EndsWith("0")).ToList();
			}
			else if (!String.IsNullOrEmpty(flgTipo) && flgTipo.Equals("Q"))
			{
				dados = dados.Where(x => !x.CodLinha.EndsWith("0")).ToList();
			}

			return View(dados);
		}

		//
		// GET: /Outros/Linha/Create
		public ActionResult Create()
		{
			return View();
		}

		//
		// POST: /Outros/Linha/Create
		[HttpPost]
		public ActionResult Create(LinhaDTO linha)
		{
			try
			{
				CadLinha.GravarLinha(linha);

				return Json(true, JsonRequestBehavior.AllowGet);
			}
			catch
			{
				return Json(false, JsonRequestBehavior.AllowGet);
			}
		}

		//
		// GET: /Outros/Linha/Edit/5
		public ActionResult Edit(string codLinha)
		{
			var dado = CadLinha.ObterLinha(codLinha);

			return View(dado);
		}

		//
		// POST: /Outros/Linha/Edit/5
		[HttpPost]
		public ActionResult Edit(LinhaDTO linha)
		{
			try
			{
				CadLinha.GravarLinha(linha);

				return Json(true, JsonRequestBehavior.AllowGet);
			}
			catch
			{
				return Json(false, JsonRequestBehavior.AllowGet);
			}
		}

		//
		// GET: /Outros/Linha/Delete/5
		public ActionResult Delete(string codLinha)
		{
			var dado = CadLinha.ObterLinha(codLinha);

			return View(dado);
		}

		//
		// POST: /Outros/Linha/Delete/5
		[HttpPost]
		public ActionResult Delete(LinhaDTO linha)
		{
			try
			{
				CadLinha.RemoverLinha(linha.CodLinha);

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}
	}
}

SEMP.UI/Areas/Coleta/Views/Configuracao/AddLinha.cshtml
@model SEMP.Model.DTO.CBLinhaDTO

@{
	ViewBag.Title = "Adicionar Linha";
	Layout = "~/Views/Shared/_Layout.cshtml";

	var retornologin = (SEMP.Model.VO.RetornoLogin)Session["RetornoLogin"];
	ViewBag.Sistema = "Rastreabilidade";
	ViewBag.Rotina = "Configuração";
	if (retornologin != null)
	{
		ViewBag.NomeUsuario = retornologin.NomFuncionario;
	}

	var fases = (List<string>)ViewBag.fases;

	List<SelectListItem> listSetorOrigem = new List<SelectListItem>();

	if (fases != null)
	{
		fases.ForEach(x => listSetorOrigem.Add(new SelectListItem() { Text = x, Value = x }));
	}
	else
	{

		listSetorOrigem.Add(new SelectListItem { Text = "IAC", Value = "IAC" });
		listSetorOrigem.Add(new SelectListItem { Text = "IMC", Value = "IMC" });
		listSetorOrigem.Add(new SelectListItem { Text = "FEC", Value = "FEC" });
		listSetorOrigem.Add(new SelectListItem { Text = "TEC", Value = "TEC" });
		listSetorOrigem.Add(new SelectListItem { Text = "LCM", Value = "LCM" });
		listSetorOrigem.Add(new SelectListItem { Text = "DAT", Value = "DAT" });
		listSetorOrigem.Add(new SelectListItem { Text = "RMA", Value = "RMA" });
		listSetorOrigem.Add(new SelectListItem { Text = "MOB", Value = "MOB" });
	}

	List<SelectListItem> listSetor = new List<SelectListItem>();

	if (fases != null)
	{
		fases.ForEach(x => listSetor.Add(new SelectListItem() { Text = x, Value = x }));
	}
	else
	{

		listSetor.Add(new SelectListItem { Text = "IAC", Value = "IAC" });
		listSetor.Add(new SelectListItem { Text = "IMC", Value = "IMC" });
		listSetor.Add(new SelectListItem { Text = "FEC", Value = "FEC" });
		listSetor.Add(new SelectListItem { Text = "TEC", Value = "TEC" });
		listSetor.Add(new SelectListItem { Text = "LCM", Value = "LCM" });
		listSetor.Add(new SelectListItem { Text = "DAT", Value = "DAT" });
		listSetor.Add(new SelectListItem { Text = "RMA", Value = "RMA" });
		listSetor.Add(new SelectListItem { Text = "MOB", Value = "MOB" });
	}

	List<SelectListItem> listFamilia = new List<SelectListItem>();
	listFamilia.Add(new SelectListItem { Text = "AUD", Value = "AUD" });
	listFamilia.Add(new SelectListItem { Text = "DVD", Value = "DVD" });
	listFamilia.Add(new SelectListItem { Text = "LCD", Value = "LCD" });
	listFamilia.Add(new SelectListItem { Text = "INF", Value = "INF" });
	listFamilia.Add(new SelectListItem { Text = "TAB", Value = "TAB" });
	listFamilia.Add(new SelectListItem { Text = "TV", Value = "TV" });
	listFamilia.Add(new SelectListItem { Text = "LCM", Value = "LCM" });
	listFamilia.Add(new SelectListItem { Text = "DAT", Value = "DAT" });
	listFamilia.Add(new SelectListItem { Text = "RMA", Value = "RMA" });
	listFamilia.Add(new SelectListItem { Text = "TEC", Value = "TEC" });
	listFamilia.Add(new SelectListItem { Text = "CEL", Value = "CEL" });

	var statusAtivo = "off";


}

<script src="@Scripts.Url("~/Scripts/jquery.maskedinput.js")" type="text/javascript"></script>

<h2>Criar Linha</h2>
@using (Html.BeginForm("AddLinha", "Configuracao", FormMethod.Post, new { id = "FormAddLinha", @onsubmit = "return false;", @class = "container-fluid" }))
{
	@Html.AntiForgeryToken()
	@Html.ValidationSummary(true)
<div class="row">
	<div class="col-md-4">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="pull-right">
					<label>Ativo:</label>
					<div class="pull-right" style="margin-top: 2px; margin-right: 2px;">
						<a href="#" id="tglFlgAtivo" class="toggler @statusAtivo">&nbsp;</a>
						<input type="hidden" value="0" id="FlgAtivo" name="FlgAtivo" />
					</div>
				</div>
				<h4 style="margin: 0;">Dados da Linha</h4>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-4">
						<div class="editor-label" style="font-size:14px">Código</div>
						<div class="editor-field">
							@Html.EditorFor(model => model.CodLinha, new { htmlAttributes = new { @class = "form-control input-sm", @placeholder = "Ex: 36", id = "CodLinha" } })
							@Html.ValidationMessageFor(model => model.CodLinha)
						</div>
					</div>
					<div class="col-md-8">
						<div class="editor-label" style="font-size:14px">Descrição da Linha</div>
						<div class="editor-field">
							@Html.EditorFor(model => model.DesLinha, new { htmlAttributes = new { @class = "form-control input-sm", maxlength = 50, @placeholder = "Ex: Linha 01 LCD" } })
							@Html.ValidationMessageFor(model => model.DesLinha)
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="editor-label" style="font-size:14px">Observação</div>
						<div class="editor-field">
							@Html.EditorFor(model => model.DesObs, new { htmlAttributes = new { @class = "form-control input-sm", maxlength = 50, @placeholder = "Ex: Linha LCD" } })
							@Html.ValidationMessageFor(model => model.DesObs)
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-3">
						<div class="editor-label" style="font-size:14px">Setor</div>
						<div class="editor-field">
							@Html.DropDownList("Setor", listSetor, "", new { @class = "form-control input-sm" })
							@Html.ValidationMessageFor(model => model.Setor)
						</div>
					</div>
					<div class="col-md-3">
						<div class="editor-label" style="font-size:14px">Família</div>
						<div class="editor-field">
							@Html.DropDownList("Familia", listFamilia, "", new { @class = "form-control input-sm" })
							@Html.ValidationMessageFor(model => model.Familia)
						</div>
					</div>

					<div class="col-md-6">
						<div class="editor-label" style="font-size:14px">Código SEMP</div>
						<div class="editor-field">
							@Html.EditorFor(model => model.CodLinhaT1, new { htmlAttributes = new { @class = "form-control input-sm", @placeholder = "Ex: 101.28-0", id = "CodLinhaT1" } })
							@Html.ValidationMessageFor(model => model.CodLinhaT1)
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-4">
						<div class="editor-label" style="font-size:14px">Setor Origem</div>
						<div class="editor-field">
							@Html.DropDownList("SetorOrigem", listSetorOrigem, "", new { @class = "form-control input-sm" })
							@Html.ValidationMessageFor(model => model.SetorOrigem)
						</div>
					</div>
					<div class="col-md-4">
						<div class="editor-label" style="font-size:14px">Linha Origem</div>
						<div class="editor-field">
							<select name="CodLinhaOrigem" id="CodLinhaOrigem" class="form-control input-sm"></select>
						</div>
					</div>
				</div>
				<hr />
				<div class="row">
					<div class="col-md-6">
						<div class="editor-label" style="font-size:14px">Tam. do Magazine</div>
						<div><input type="text" name="tamMagazine" id="tamMagazine" class="form-control input-sm" placeholder="Ex: 25" style="font-size:14px"></div>
					</div>
					<div class="col-md-6">
						<div class="editor-label" style="font-size:14px">Tamanho do Lote</div>
						<div><input type="text" name="tamLote" id="tamLote" class="form-control input-sm" placeholder="Ex: 25" style="font-size:14px"></div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-3">
		<div class="panel panel-info">
			<div class="panel-heading"><h4 style="margin: 0;">Horário de Funcionamento</h4></div>
			<div class="panel-body" id="pnlHorarios">
				<div id="comboBox_HorarioLinha" style="font-size:14px">
					<form name="combo_box">
						<table>
							<tr>
								<td><select multiple size="10" class="form-control" name="FromLB" id="FromLB" style="width:140px"></select></td>
								<td>
									<button type="button" onClick="move(this.form.FromLB, this.form.ToLB)" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-chevron-right"></i></button><br />
									<button type="button" onClick="move(this.form.ToLB, this.form.FromLB)" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-chevron-left"></i></button>
								</td>
								<td>
									<select multiple size="10" class="form-control" name="ToLB" id="ToLB" style="width:140px"></select>
								</td>
							</tr>
						</table>
					</form>
				</div>
			</div>
		</div>
	</div>

</div>

}

<div style="margin-bottom:20px" class="btn-group">
	<input class="btn btn-sm btn-danger" type="button" value="Voltar" id="btnVoltar" style="margin-bottom:20px" onclick="location.href = '/Coleta/Configuracao/Linha/'" />
	<input class="btn btn-sm btn-primary" type="button" value="Criar Linha" onclick="criarLinha()" />
</div>

<script>

	@{WriteLiteral(ViewBag.JS);}

	var codDRT = '@retornologin.CodDRT';

	jQuery(function ($) {
		$("#CodLinhaT1").mask("999.99-9", { placeholder: " " });
	});

	jQuery(function ($) {
		$("#tamLote").mask("99", { placeholder: " " });
	});

	$(document).ready(function () {
		$.ajax({
			type: "GET",
			url: "/Configuracao/ObterHorarios/",
			data: {  },
			dataType: "json",
			success: function (json) {
				var options = "";
				options += '<optgroup label = "Horários">';
				$.each(json, function (key, Horario) {
					options += '<option value="' + Horario.idHorario + '">' + Horario.HoraInicio + ' - ' + Horario.HoraFim + '</option>';
				});
				$("#FromLB").html(options);
			}
		});

		CarregarLinhas();
	});

	function move(tbFrom, tbTo) {
		var arrFrom = new Array(); var arrTo = new Array();
		var arrLU = new Array();
		var i;
		for (i = 0; i < tbTo.options.length; i++) {
			arrLU[tbTo.options[i].text] = tbTo.options[i].value;
			arrTo[i] = tbTo.options[i].text;
		}
		var fLength = 0;
		var tLength = arrTo.length;
		for (i = 0; i < tbFrom.options.length; i++) {
			arrLU[tbFrom.options[i].text] = tbFrom.options[i].value;
			if (tbFrom.options[i].selected && tbFrom.options[i].value != "") {
				arrTo[tLength] = tbFrom.options[i].text;
				tLength++;
			}
			else {
				arrFrom[fLength] = tbFrom.options[i].text;
				fLength++;
			}
		}

		tbFrom.length = 0;
		tbTo.length = 0;
		var ii;

		for (ii = 0; ii < arrFrom.length; ii++) {
			var no = new Option();
			no.value = arrLU[arrFrom[ii]];
			no.text = arrFrom[ii];
			tbFrom[ii] = no;
		}

		for (ii = 0; ii < arrTo.length; ii++) {
			var no = new Option();
			no.value = arrLU[arrTo[ii]];
			no.text = arrTo[ii];
			tbTo[ii] = no;
		}
	}

	function criarLinha(){

		if ($("#tamMagazine").val() == null || $("#tamMagazine").val() == "") {
			alert("O Campo Tamanho do Magazine está vazio");
			return;
		}

		if ($("#tamLote").val() == null || $("#tamLote").val() == "") {
			alert("O Campo Tamanho do Lote está vazio");
			return;
		} else if ($("#ToLB").length <= 0) {
			alert("O horário de linha deve estar preenchido");
			return;
		}


		$.ajax({
			type: "GET",
			url: "/Configuracao/InserirLoteLinha/",
			data: { CodLinha: $("#CodLinha").val(), TamLote: $("#tamLote").val(), TamMagazine: $("#tamMagazine").val(), CodDRT: codDRT },
			dataType: "json",
			success: function (json) {

			},
			error: function (xhr) {
				fn_error(xhr);
			}
		});

		var x = document.getElementById('ToLB');

		var txt = "";
		var val = "";
		var valores = "";

		for (var i = 0; i < x.length; i++) {

			txt = x[i].text;
			val = x[i].value;

			valores +=val+"|";
		}

		$.ajax({
			type: "GET",
			url: "/Configuracao/InserirHorarioLinha/",
			data: { CodLinha: $("#CodLinha").val(), IdHorario: valores.substring(0, (valores.trim().length - 1)), Setor: $("#Setor").val(), CodLinhaT1: $("#CodLinhaT1").val() },
			dataType: "json",
			success: function (json) {
				document.forms["FormAddLinha"].submit();
			},
			error: function (xhr) {
				fn_error(xhr);
			}
		});

	}

	$('a.toggler').click(function () {

		var eu = $(this);
		var estado = eu.hasClass('off');

		if (estado) {
			$("#FlgAtivo").val("1");
		}
		else {
			$("#FlgAtivo").val("0");
		}

		eu.toggleClass('off');

	});

	$('#SetorOrigem').change(CarregarLinhas);

	function CarregarLinhas() {

		$("#CodLinhaOrigem").html("<option>Carregando...</option>");

		var fase = $("#SetorOrigem").val();

		$.ajax({
			type: "GET",
			url: "/posto/GetLinhas/",
			data: { fabrica: fase },
			dataType: "json",
			success: function (json) {
				var options = "";
				options += '<option value="" selected> [ LINHA ] </option>';

				$.each(json, function (key, Linhas) {
					options += '<option value="' + Linhas.CodLinha + '">' + Linhas.DesLinha + '</option>';

					selected = "";
				});

				options += '<option value="0"> [ TODAS ] </option>';

				$("#CodLinhaOrigem").html(options);
			}
		});
	}

</script>


<div style="margin-bottom:20px">

</div>