SEMP.UI/Areas/Coleta/Controllers/OrigemController.cs
using System.Web.Mvc;
using RAST.BO.Rastreabilidade;
using SEMP.Model.DTO;

namespace SEMP.Areas.Coleta.Controllers
{
	public class OrigemController : Controller
	{
		//
		// GET: /Coleta/Origem/
		public ActionResult Index()
		{
			var origens = Defeito.ObterOrigens();

			return View(origens);
		}

		//
		// GET: /Coleta/Origem/Create
		public ActionResult Create()
		{
			return View();
		}

		//
		// POST: /Coleta/Origem/Create
		[HttpPost]
		public ActionResult Create(CBCadOrigemDTO origem)
		{
			try
			{
				var codigo = Defeito.ObterUltimaOrigem();

                var flgAtivo = Request.Form["FlgAtivo"];
                origem.FlgAtivo = flgAtivo == null ? false : true;

				codigo++;

				origem.CodOrigem = codigo.ToString();

				Defeito.GravarOrigem(origem);

				return Json(true, JsonRequestBehavior.AllowGet);
			}
			catch
			{
				return Json(false, JsonRequestBehavior.AllowGet);
			}
		}

		//
		// GET: /Coleta/Origem/Edit/5
		public ActionResult Edit(string codOrigem)
		{
			var origem = Defeito.ObterOrigem(codOrigem);

			return View(origem);
		}

		//
		// POST: /Coleta/Origem/Edit/5
		[HttpPost]
		public ActionResult Edit(CBCadOrigemDTO origem)
		{
			try
			{
                var flgAtivo = Request.Form["FlgAtivo"];
                origem.FlgAtivo = flgAtivo == null ? false : true;

				Defeito.GravarOrigem(origem);

				return Json(true, JsonRequestBehavior.AllowGet);
			}
			catch
			{
				return Json(false, JsonRequestBehavior.AllowGet);
			}
		}

		//
		// GET: /Coleta/Origem/Delete/5
		public ActionResult Delete(string codOrigem)
		{
			var origem = Defeito.ObterOrigem(codOrigem);

			return View(origem);
		}

		//
		// POST: /Coleta/Origem/Delete/5
		[HttpPost]
		public ActionResult Delete(CBCadOrigemDTO origem)
		{
			try
			{
				Defeito.RemoverOrigem(origem);

				return RedirectToAction("Index");
			}
			catch
			{
				return RedirectToAction("Index");
			}
		}
	}
}

SEMP.UI/Areas/Coleta/Views/Origem/Create.cshtml
@model SEMP.Model.DTO.CBCadOrigemDTO

@using (Html.BeginForm("Create", "Origem", FormMethod.Post, new { @class = "form-inline", @role = "form", @name = "frmOrigem", id = "frmOrigem" }))
{
	@Html.AntiForgeryToken()
	
	<div class="form-horizontal">
		@Html.ValidationSummary(true)
		@Html.HiddenFor(model => model.CodOrigem)
		<div class="row">
			<div class="form-group">
				@Html.LabelFor(model => model.DesOrigem, new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.TextBoxFor(model => model.DesOrigem)
					@Html.ValidationMessageFor(model => model.DesOrigem)
				</div>
			</div>
		</div>
        <div class="row" style="margin-left: 15px;">
			<div class="form-group">
				<div class="input-group">
					 @Html.LabelFor(model => model.FlgAtivo)
                    @Html.CheckBoxFor(model => model.FlgAtivo.Value)
                    @Html.ValidationMessageFor(model => model.FlgAtivo)
				</div>
			</div>
		</div>
        <div class="row" style="margin-left: 15px;">
            <div class="form-group">
				<div style="margin-top: 10px; display: inline-block;">
					@Html.ActionLink("Retornar", "Index", null, new { @class = "bttn bttn-sm bttn-red", @style = "color: white; text-decoration: none;" })
				</div>
				<div style="display: inline-block;">
					<input type="button" value="Gravar" class="bttn bttn-sm bttn-red" onclick="gravar()" />
				</div>
			</div>
        </div>
	</div>
}

<script>
	function gravar() {
		$.ajax({
			type: "POST",
			url: "/Origem/Create/",
			data: $("#frmOrigem").serialize(),
			dataType: "json",
			success: function (json) {
				if (json == true) {
					alert("Origem inserida com sucesso.");
					$("#DesOrigem").val("");
				} else {
					alert("Não foi possível gravar.");
				}
			},
			error: function (xhr) {
				alert("Não foi possível adicionar: " + xhr);
			}
		});
	}

</script>

SEMP.UI/Areas/Coleta/Views/Origem/Delete.cshtml
@model SEMP.Model.DTO.CBCadOrigemDTO

<h4>Tem certeza de que deseja remover esse registro?</h4>
<div>
	<dl class="dl-horizontal">
		<dt>@Html.DisplayNameFor(model => model.CodOrigem)</dt>
		<dd>@Html.DisplayFor(model => model.CodOrigem)</dd>
		<dt>@Html.DisplayNameFor(model => model.DesOrigem)</dt>
		<dd>@Html.DisplayFor(model => model.DesOrigem)</dd>
	</dl>

	@using (Html.BeginForm())
 {
		@Html.AntiForgeryToken()

		<div class="form-actions no-color">
			<div style="margin-top: 10px; display: inline-block;">
				@Html.ActionLink("Retornar", "Index", null, new { @class = "bttn bttn-sm bttn-red", @style = "color: white; text-decoration: none;" })
			</div>
			<div style="display: inline-block;">
				<input type="submit" value="Apagar" class="bttn bttn-sm bttn-red" />
			</div>
		</div>
 }
</div>

SEMP.UI/Areas/Coleta/Views/Origem/Edit.cshtml
@model SEMP.Model.DTO.CBCadOrigemDTO

@using (Html.BeginForm("Edit", "Origem", FormMethod.Post, new { @class = "form-inline", @role = "form", @id = "frmOrigem", @name = "frmOrigem" }))
{
	@Html.AntiForgeryToken()
	
	<div class="form-horizontal">
		@Html.ValidationSummary(true)
		<div class="row" style="margin-left: 15px;">
			<div class="form-group">
				<div class="input-group">
					@Html.LabelFor(model => model.CodOrigem)
					@Html.TextBoxFor(model => model.CodOrigem, new { @readonly = "readonly", @style="width: 30px"})
					@Html.ValidationMessageFor(model => model.CodOrigem)
				</div>
			</div>
		</div>
		<div class="row" style="margin-left: 15px;">
			<div class="form-group">
				<div class="input-group">
					@Html.LabelFor(model => model.DesOrigem)
					@Html.TextBoxFor(model => model.DesOrigem)
					@Html.ValidationMessageFor(model => model.DesOrigem)
				</div>
			</div>
		</div>
        <div class="row" style="margin-left: 15px;">
			<div class="form-group">
				<div class="input-group">
					 @Html.LabelFor(model => model.FlgAtivo)
                    <input type="checkbox" name="FlgAtivo" id="FlgAtivo" @(Model.FlgAtivo.Value == true ? "checked='checked'" : "") />
                    @Html.ValidationMessageFor(model => model.FlgAtivo)
				</div>
			</div>
		</div>
		<div class="row" style="margin-left: 15px;">
			<div class="form-group">
				<div style="margin-top: 10px; display: inline-block;">
					@Html.ActionLink("Retornar", "Index", null, new { @class = "bttn bttn-sm bttn-red", @style = "color: white; text-decoration: none;" })
				</div>
				<div style="display: inline-block;">
					<input type="button" value="Gravar" class="bttn bttn-sm bttn-red" onclick="gravar()" />
				</div>
			</div>
		</div>
	</div>
}
<script>
	function gravar() {
		$.ajax({
			type: "POST",
			url: "/Origem/Edit/",
			data: $("#frmOrigem").serialize(),
			dataType: "json",
			success: function (json) {
				if (json == true) {
					alert("Origem alterada com sucesso.");
					document.location.href = "/Coleta/Origem/";
				} else {
					alert("Não foi possível gravar.");
				}
			},
			error: function (xhr) {
				alert("Não foi possível alterar: " + xhr);
			}
		});
	}

</script>

SEMP.UI/Areas/Coleta/Views/Origem/Index.cshtml
@model IEnumerable<SEMP.Model.DTO.CBCadOrigemDTO>

@{
	ViewBag.Title = "Listagem de Origem";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewBag.Sistema = "Rastreabilidade";
	ViewBag.Rotina = "Relatório Técnico";
}
@Scripts.Render("~/bundles/excelexport")

<h3>@ViewBag.Title</h3>

<div id="dialog-edit" style="display: none; top: 10px;"></div>

<p>
	<input type="button" id="btnExportar" name="btnExportar" value="Exportar Excel" class="bttn bttn-sm bttn-green" />
	<input type="button" name="btnNovo" id="btnNovo" value="Novo" class="bttn bttn-sm bttn-red" />
	<input type="button" name="btnEnviar" value="Consultar" class="bttn bttn-sm bttn-red" onclick="document.location.reload();" />
</p>
<table class="table-semp" id="tblDados">
	<thead>
		<tr>
			<th style="width: 100px;"></th>
			<th style="width: 60px;">@Html.DisplayNameFor(model => model.CodOrigem)</th>
			<th>@Html.DisplayNameFor(model => model.DesOrigem)</th>
		</tr>
	</thead>
	<tbody>
	@foreach (var item in Model) {
		<tr>
			<td>
				@Html.ActionLink("Alterar", "Edit", new { codOrigem =item.CodOrigem }, new { @class = "lnkEdit" }) |
				@Html.ActionLink("Apagar", "Delete", new { codOrigem =item.CodOrigem }, new { @class = "lnkEdit" })
			</td>
			<td>@Html.DisplayFor(modelItem => item.CodOrigem)</td>
			<td>@Html.DisplayFor(modelItem => item.DesOrigem)</td>
		</tr>
	}
	</tbody>
</table>
<br /><br/>

<script>
	$(document).ready(function () {
		$("#btnExportar").click(function () {

			$("#tblDados").btechco_excelexport({
				containerid: "tblDados",
				datatype: $datatype.MVC
			});
		});

		var url = "";

		$("#dialog-edit").dialog({
			title: 'Editar Origem',
			autoOpen: false,
			resizable: false,
			width: 400,
			height: 200,
			top: 0,
			show: { effect: 'drop', direction: "up" },
			modal: true,
			draggable: true,
			open: function (event, ui) {
				$(".ui-dialog-titlebar-close").hide();
				$(this).html("");
				$(this).load(url);
			}
		});

		$(".lnkEdit").on("click", function (e) {
			// e.preventDefault(); use this or return false
			url = $(this).attr('href');
			$(".ui-dialog-title").html("Editar origem");
			$("#dialog-edit").dialog('open');
			$("#dialog-edit").css("height", 220);

			return false;
		});

		$("#btnNovo").on("click", function (e) {
			// e.preventDefault(); use this or return false
			url = "/Coleta/Origem/Create/";
			$(".ui-dialog-title").html("Nova origem");
			$("#dialog-edit").dialog('open');

			return false;
		});

		$("#btnclose").on("click", function (e) {
			$("#dialog-edit").dialog("close");
			return false;
		});

	});

</script>